import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    NODE_ENV: z.enum(['development', 'test', 'production']),
    BETTER_AUTH_SECRET: z.string().min(32),
    BETTER_AUTH_URL: z.string().url(),
    RESEND_API_KEY: z.string().min(1),
    EMAIL_FROM: z.string().min(1).optional(),
    UPSTASH_REDIS_REST_URL: z.string().url().optional(),
    UPSTASH_REDIS_REST_TOKEN: z.string().min(1).optional(),
    R2_ACCOUNT_ID: z.string().min(1).optional(),
    R2_ACCESS_KEY_ID: z.string().min(1).optional(),
    R2_SECRET_ACCESS_KEY: z.string().min(1).optional(),
    R2_BUCKET_NAME: z.string().min(1).optional(),
    R2_PUBLIC_BASE_URL: z.string().url().optional(),
    GOOGLE_CLIENT_ID: z.string().min(1).optional(),
    GOOGLE_CLIENT_SECRET: z.string().min(1).optional(),
    VERCEL_PROJECT_ID: z.string().min(1).optional(),
    VERCEL_TEAM_ID: z.string().min(1).optional(),
    VERCEL_TOKEN: z.string().min(1).optional(),
    ADMIN_EMAILS: z.string().optional(),
    SUPPORT_COMMISSION_BPS: z.coerce
      .number()
      .int()
      .min(0)
      .max(5_000)
      .default(1000),
    MOMO_BASE_URL: z.string().url().optional(),
    MOMO_TARGET_ENVIRONMENT: z.string().min(1).optional(),
    MOMO_COLLECTION_SUBSCRIPTION_KEY: z.string().min(1).optional(),
    MOMO_API_USER: z.string().min(1).optional(),
    MOMO_API_KEY: z.string().min(1).optional(),
    MOMO_CURRENCY: z.string().min(1).optional(),
    MOMO_COUNTRY: z.string().length(2).optional(),
    AIRTEL_BASE_URL: z.string().url().optional(),
    AIRTEL_CLIENT_ID: z.string().min(1).optional(),
    AIRTEL_CLIENT_SECRET: z.string().min(1).optional(),
    AIRTEL_COUNTRY: z.string().min(1).optional(),
    AIRTEL_CURRENCY: z.string().min(1).optional(),
    // Bearer token for /api/cron/*. Vercel sends Authorization: Bearer <value>
    // only when this is set; the routes return 401 otherwise. Min 16 chars.
    CRON_SECRET: z.string().min(16).optional(),
    PAYMENTS_WEBHOOK_SECRET: z.string().min(16).optional(),
    // Nyole hosted checkout (card + mobile money). Secret key af_(test|live)_sec_…
    NYOLE_SECRET_KEY: z.string().min(1).optional(),
    NYOLE_BASE_URL: z.string().url().optional(),
  },
  client: {
    NEXT_PUBLIC_URL: z.string(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    NODE_ENV: process.env.NODE_ENV,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
    NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    EMAIL_FROM: process.env.EMAIL_FROM || undefined,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL || undefined,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN || undefined,
    R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID || undefined,
    R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID || undefined,
    R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY || undefined,
    R2_BUCKET_NAME: process.env.R2_BUCKET_NAME || undefined,
    R2_PUBLIC_BASE_URL: process.env.R2_PUBLIC_BASE_URL || undefined,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || undefined,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET || undefined,
    VERCEL_PROJECT_ID: process.env.VERCEL_PROJECT_ID || undefined,
    VERCEL_TEAM_ID: process.env.VERCEL_TEAM_ID || undefined,
    VERCEL_TOKEN: process.env.VERCEL_TOKEN || undefined,
    ADMIN_EMAILS: process.env.ADMIN_EMAILS || undefined,
    SUPPORT_COMMISSION_BPS: process.env.SUPPORT_COMMISSION_BPS || undefined,
    MOMO_BASE_URL: process.env.MOMO_BASE_URL || undefined,
    MOMO_TARGET_ENVIRONMENT: process.env.MOMO_TARGET_ENVIRONMENT || undefined,
    MOMO_COLLECTION_SUBSCRIPTION_KEY:
      process.env.MOMO_COLLECTION_SUBSCRIPTION_KEY || undefined,
    MOMO_API_USER: process.env.MOMO_API_USER || undefined,
    MOMO_API_KEY: process.env.MOMO_API_KEY || undefined,
    MOMO_CURRENCY: process.env.MOMO_CURRENCY || undefined,
    MOMO_COUNTRY: process.env.MOMO_COUNTRY || undefined,
    AIRTEL_BASE_URL: process.env.AIRTEL_BASE_URL || undefined,
    AIRTEL_CLIENT_ID: process.env.AIRTEL_CLIENT_ID || undefined,
    AIRTEL_CLIENT_SECRET: process.env.AIRTEL_CLIENT_SECRET || undefined,
    AIRTEL_COUNTRY: process.env.AIRTEL_COUNTRY || undefined,
    AIRTEL_CURRENCY: process.env.AIRTEL_CURRENCY || undefined,
    CRON_SECRET: process.env.CRON_SECRET || undefined,
    PAYMENTS_WEBHOOK_SECRET: process.env.PAYMENTS_WEBHOOK_SECRET || undefined,
    NYOLE_SECRET_KEY: process.env.NYOLE_SECRET_KEY || undefined,
    NYOLE_BASE_URL: process.env.NYOLE_BASE_URL || undefined,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
